version: '3.8'

services:
  music-web-gd:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: music-web-gd
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
